import fs from 'fs';

try {
  const content = fs.readFileSync('wrangler.jsonc', 'utf8');
  // Strip single-line and multi-line comments from JSONC to parse safely
  const cleanJson = content.replace(/\/\*[\s\S]*?\*\/|([^\\:]|^)\/\/.*$/gm, '$1');
  const config = JSON.parse(cleanJson);

  if (config.vars) {
    let envContent = '# Generated by build-env.js from wrangler.jsonc vars\n';
    for (const [key, val] of Object.entries(config.vars)) {
      envContent += `${key}="${val}"\n`;
    }
    fs.writeFileSync('.env', envContent, 'utf8');
    console.log('Generated .env file from wrangler.jsonc vars successfully.');
  } else {
    console.log('No vars found in wrangler.jsonc.');
  }
} catch (err) {
  console.error('Error generating .env file:', err);
  process.exit(1);
}
